# headers and icon 
title: anastasiia khazova
info: lecturer and phd student @ hse
icon-pic: assets/img/mandu_icon.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
